version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      GOOGLE_SHEET_ID: "your_sheet_id"
      GOOGLE_CLIENT_ID: "your_client_id"
      GOOGLE_CLIENT_SECRET: "your_client_secret"
      GOOGLE_DRIVE_FOLDER_ID: "your_folder_id"
    volumes:
      - ./path/to/credentials.json:/app/credentials.json:ro
