services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        GOOGLE_SHEET_ID: "your_sheet_id"
        GOOGLE_CLIENT_ID: "your_client_id"
        GOOGLE_CLIENT_SECRET: "your_client_secret"
        GOOGLE_DRIVE_FOLDER_ID: "your_folder_id"
    ports:
      - "8080:8080"
    environment:
      GOOGLE_SHEET_ID: "your_sheet_id"
      GOOGLE_CLIENT_ID: "your_client_id"
      GOOGLE_CLIENT_SECRET: "your_client_secret"
      GOOGLE_DRIVE_FOLDER_ID: "your_folder_id"
      GOOGLE_APPLICATION_CREDENTIALS: /app/credentials.json
    volumes:
      - ./backend/src/main/resources/credentials.json:/app/credentials.json:ro
